# Site settings
title: Gruuf App
email: lukasz@gruuf.com
url: https://gruuf.com/
description: "This service allows you to control history of your motorbike, keep track of incoming periodic maintenance activities and any other service activities your perform in your motorbike."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/GruufApp

# Build settings
markdown: kramdown
permalink: pretty
